# Generated by Django 5.1.4 on 2025-01-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_author_student_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school_id',
            field=models.CharField(default='N/A', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
